---
title: "Keyword Selection"
author: "Zayne Sember"
date: "11/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(stringr)
library(kableExtra)
library(xlsx)
```

```{r}
# Takes in a dataframe of keywords and a dataframe with text
# Returns dataframe of tweet counts, total and by party
keyword_count <- function(df_keys, df_text){
  count <- c()
  D.count <- c()
  R.count <- c()
  
  for(k in df_keys$word){
    t <- df_text[grep(tolower(k),tolower(df_text$tweet.text)),]
    party_counts <- as.numeric(table(t$party.code))
  
    #cat("Instances of ", k, ": ", length(t$tweet.text), "\n", sep="")
    
    count <- c(count, length(t$tweet.text))
    D.count <- c(D.count, party_counts[1])
    R.count <- c(R.count, party_counts[2])
  }
  return(data.frame(count, D.count, R.count))
}

word <- c("pandemic", "corona", "covid", "mask", " virus", "sars-cov-2", "lockdown",
           "restriction", "spread", "social distanc",
           "quarantin", "outbreak", "cluster", "wuhan", "china virus", "infect", "vaccin")

cat <- c(1,1,1,2,1,1,2,2,3,2,2,3,3,1,1,3,2)

keywords <- data.frame(word, cat) %>% arrange(cat)

count.prepandemic <- keyword_count(keywords, data.text.official.prepandemic.all) %>% 
  rename(count.pre = count,
         D.count.pre = D.count,
         R.count.pre = R.count)


count.pandemic <- keyword_count(keywords, data.text.official.covid.all) %>% 
  rename(count.pan = count,
         D.count.pan = D.count,
         R.count.pan = R.count)

kwc <- cbind(keywords, count.prepandemic, count.pandemic)
kwc[is.na(kwc)] <- 0

kwc$est.false.pos <- round(100*kwc$count.pre/(kwc$count.pan),1)

kwc <- kwc %>% arrange(cat, count.pan)

kable(kwc)

# Checking how many tweets we would be working with for a given list of keywords
# Have to avoid double-counting tweets with multiple keywords!

print("Total tweets with at least one keyword from full list:")
length(unique(Reduce(c,sapply(tolower(keywords$word), grep, tolower(data.text.official.covid.all$tweet.text)))))


kwc_lim <- kwc %>% filter(count.pan >= 500 & est.false.pos < 5)
print("Total tweets for keywords with at least 500 tweet instances and false positive under 5%:")
length(unique(Reduce(c,sapply(tolower(kwc_lim$word), grep, tolower(data.text.official.covid.all$tweet.text)))))


kwc_lim1 <- kwc %>% filter(count.pan >= 500 & est.false.pos < 5 & cat == 1)
print("Total tweets for NOMINAL keywords with at least 500 tweet instances and false positive under 5%:")
length(unique(Reduce(c,sapply(tolower(kwc_lim1$word), grep, tolower(data.text.official.covid.all$tweet.text)))))


kwc_lim2 <- kwc %>% filter(count.pan >= 500 & est.false.pos < 5 & cat == 2)
print("Total tweets for MITIGATION keywords with at least 500 tweet instances and false positive under 5%:")
length(unique(Reduce(c,sapply(tolower(kwc_lim2$word), grep, tolower(data.text.official.covid.all$tweet.text)))))


kable(kwc %>% select(word, count.pre, count.pan, est.false.pos),
      col.names=c("", "Prepandemic\ncount", "Pandemic\ncount", "Estimated\nfalse positive (%)")) %>% 
  column_spec(column=1:4,width="0.5in") %>% 
  save_kable("Tables/KeywordTable.png") 

kwc %>% filter(est.false.pos <= 5)

sum((kwc %>% filter(est.false.pos <= 5))$count.pan)

sum(kwc$count.pan) - sum((kwc %>% filter(est.false.pos <= 5))$count.pan)

# Save keywords with est false positive under 5%
keywords <- (kwc %>% filter(est.false.pos <= 5))$word
```

Reading Keyword Tweets
```{r}
rand <- sample(ohpa.total$name, 3)
rand

rand_tweets <- data.text.official.covid.all %>% filter(name %in% rand)
rand_tweets <- rand_tweets[unique(Reduce(c,sapply(tolower(kwc_lim1$word), grep, tolower(rand_tweets$tweet.text)))),]

write.xlsx(rand_tweets, "RandomMemberKeywordTweets.xlsx")
```


